### ISSUE TITLE
error: no member named 'enableSystemLinkerHack'

### ISSUE THREAD

**Issue by ernesernesto** [jeffkdev/sokol-zig-examples#2]
I could not find `enableSystemLinkerHack` on zig version 0.8.0 macosx x86-64
Might be because of this repo using latest dev repo?

Build still works fine by changing that particular line on build.zig into 
`b.env_map.put("ZIG_SYSTEM_LINKER_HACK", "1") catch unreachable;`

Thanks for the sokol imgui zig, been searching for an easy drop-in solution to play imgui with zig :)

**Comment by jeffkdev** [comment]
Cool, thanks for letting me know... the mac code actually hasn't been tested since 0.6.x I think (another developer set it all up). So that's good it works with that change! I made the fix now.
